version: 2
references:
  restore_yarn_cache: &restore_yarn_cache
    restore_cache:
      keys:
        # when lock file changes, use increasingly general patterns to restore cache
        - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
        - yarn-packages-v1-{{ .Branch }}-
        - yarn-packages-v1-

  save_yarn_cache: &save_yarn_cache
    save_cache:
      paths:
        - node_modules/
      key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}

  # ...
  # The node module cache for macos machines must
  # be separate from the other node module cache
  # because the home directory differs.
  restore_yarn_cache_macos: &restore_yarn_cache_macos
    restore_cache:
      keys:
        # when lock file changes, use increasingly general patterns to restore cache
        - yarn-packages-macos-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
        - yarn-packages-macos-v1-{{ .Branch }}-
        - yarn-packages-macos-v2-
  save_yarn_cache_macos: &save_yarn_cache_macos
    save_cache:
      paths:
        - node_modules/
      key: yarn-packages-macos-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}

  gems_cache_key_ios: &gems_cache_key_ios ios-bundle-v1-{{ checksum "Gemfile.lock" }}-{{ arch }}
  restore_gems_cache_ios: &restore_gems_cache_ios
    restore_cache:
      key: *gems_cache_key_ios
  save_gems_cache_ios: &save_gems_cache_ios
    save_cache:
      key: *gems_cache_key_ios
      paths:
        - vendor/bundle

  pods_cache_key_ios: &pods_cache_key_ios ios-pods-v1-{{ checksum "ios/Podfile.lock" }}-{{ arch }}
  restore_pods_cache_ios: &restore_pods_cache_ios
    restore_cache:
      key: *pods_cache_key_ios
  save_pods_cache_ios: &save_pods_cache_ios
    save_cache:
      key: *pods_cache_key_ios
      paths:
        - ios/Pods

jobs:
  verify:
    working_directory: ~/project
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - *restore_yarn_cache
      - run:
          name: Install node modules
          command: yarn --frozen-lockfile
      - *save_yarn_cache
      - run:
          name: Unit tests
          command: yarn test --maxWorkers=2
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules

  build_ios:
    macos:
      xcode: '10.3.0'
    working_directory: ~/project
    environment:
      FL_OUTPUT_DIR: output
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - *restore_pods_cache_ios
      - run:
          name: Fetch CocoaPods Specs
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run:
          name: Install Pods
          command: pod install --verbose
          working_directory: ios
      - *save_pods_cache_ios
      - *restore_yarn_cache_macos
      - run:
          name: Install node modules
          command: yarn --frozen-lockfile
      - *save_yarn_cache_macos
      - *restore_gems_cache_ios
      - run:
          name: Bundle install
          command: bundle install
          working_directory: ios
      - *save_gems_cache_ios
      - run:
          name: Build iOS ipa
          command: bundle exec fastlane assemble_ios_build
          working_directory: ios
          no_output_timeout: 30m

      - store_artifacts:
          path: ios/output/gym/Serto.ipa
          destination: /Serto.ipa
  # ...
  deploy_ios:
    macos:
      xcode: '10.3.0'
    working_directory: ~/project
    environment:
      FL_OUTPUT_DIR: output
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - *restore_yarn_cache_macos
      - run:
          name: Install node modules
          command: yarn --frozen-lockfile
      - *save_yarn_cache_macos

      - *restore_gems_cache_ios
      - run:
          command: bundle install
          working_directory: ios
      - *save_gems_cache_ios

      - run:
          name: Deploy iOS ipa
          command: bundle exec fastlane deploy
          working_directory: ios
          no_output_timeout: 10m

workflows:
  version: 2
  deploy:
    jobs:
      - verify:
          # This job runs on all branches
          # and for all tags
          filters:
            tags:
              only:
                - /\d+\.\d+\.\d+/
      - build_ios:
          requires:
            - verify
      # - deploy_ios:
      #     requires:
      #       - verify
      #     # This job runs on the
      #     # deploy-ios branch
      #     # and for tags
      #     filters:
      #       branches:
      #         only:
      #           - deploy-ios
      #       tags:
      #         only:
      #           - /\d+\.\d+\.\d+/
      # - deploy_android:
      #     requires:
      #       - verify
      #     # This job runs on the
      #     # deploy-android branch
      #     # and for tags
      #     filters:
      #       branches:
      #         only:
      #           - deploy-android
      #       tags:
      #         only:
      #           - /\d+\.\d+\.\d+/
