version: 2
jobs:
  #First job, checkouts code and node deps and run unit tests
  setup-and-unit-test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      # Restore dependencies cache
      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "package.json" }}
      # Install dependencies and
      - run:
          name: install-dependencies
          command: |
            sudo npm i -g codecov
            npm i
      # Save dependencies cache
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      # Run unit tests and codecoverage
      - run:
          name: test
          command: npm test && codecov
      # Send codecoverage report to codecov.io (Needs the CODECOV_TOKEN env for private repo)
      - run:
          name: code-coverage
          command: bash <(curl -s https://codecov.io/bash)

  #Build android version
  build-android:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8.10
    steps:
      - run:
          name: package react-native android bundle independently
          command: npm run package-android --max-workers=3

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - setup-and-unit-test
      - build-android:
        requires:
          - setup-and-unit-test
