version: 2
jobs:
  #First job, checkouts code and node deps
  checkout-setup:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      # Restore dependencies cache
      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "package.json" }}
      # Install dependencies and
      - run:
          name: install-dependencies
          command: |
            sudo npm i -g codecov
            npm i
      # Save dependencies cache
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      # Persist data
      - persist_to_workspace:
          root: ~/repo
          paths:
            - ./

  #Run unit tests
  unit-tests:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8.10
    steps:
      - attach_workspace:
          at: ~/repo
      # Run unit tests and codecoverage
      - run:
          name: test
          command: npm test && codecov
      # Send codecoverage report to codecov.io (Needs the CODECOV_TOKEN env for private repo)
      - run:
          name: code-coverage
          command: bash <(curl -s https://codecov.io/bash)
      - store_test_results:
          path: test-results
  #Run android buils
  android-build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8.10
    steps:
      - attach_workspace:
          at: ~/repo
      # Run package-android
      - run:
          name: package-android
          command: npm run package-android --max-workers=3
      # Persist generated data to workspace
      - persist_to_workspace:
          root: ~/repo
          paths:
            - android/app/build/jsbundle/assets
            - android/app/build/jsbundle/res

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout-setup
      - unit-tests:
          requires:
            - checkout-setup
      - android-build:
          requires:
            - checkout-setup
